"""Pure byte-format tests for the JUCE VST3 host-state wrapper.

No Vital, no DawDreamer, no plugin host required — these test the
``VC2!``-frame + base64 codec against hand-derived vectors and synthetic
fixtures, so they run (and must pass) regardless of whether a real Vital
build is available in this environment.

See ``render.py``'s "JUCE VST3 wrapper" section for the format itself, and
``docs/decisions.md`` / the phase-0 investigation for the primary-source
citations (Vital's ``synth_plugin.cpp``, JUCE's ``juce_AudioProcessor.cpp``
and ``juce_MemoryBlock.cpp``) this implementation is grounded in.
"""

import json
import struct
from pathlib import Path

import pytest

from voxfl.render import (
    VC2_MAGIC,
    RenderError,
    _JUCE_B64_ALPHABET,
    juce_base64_decode,
    juce_base64_encode,
    parse_state,
)
from voxfl.vitalfile import Preset

FIXTURES = Path(__file__).parent / "fixtures"

PRESET_JSON = json.dumps(
    {"preset_name": "X", "synth_version": "1.5.5", "settings": {"volume": 0.5}}
).encode()


# ------------------------------------------------------------ base64 codec

def test_juce_base64_alphabet_is_nonstandard():
    assert len(_JUCE_B64_ALPHABET) == 64
    assert _JUCE_B64_ALPHABET[0] == "."
    assert _JUCE_B64_ALPHABET[63] == "+"
    assert "/" not in _JUCE_B64_ALPHABET
    assert "=" not in _JUCE_B64_ALPHABET


@pytest.mark.parametrize(
    ("data", "expected"),
    [
        # Hand-derived from JUCE's MemoryBlock::getBitRange (LSB-first,
        # 6 bits per char, byte-count-then-'.' prefix) — not generated by
        # running this implementation, so they catch bugs the round-trip
        # tests below can't (a self-consistent but wrong encode/decode pair
        # would still round-trip).
        #
        # b"A" = 0x41 = 0b01000001. chunk0 = bits[0:6] = 0b000001 = 1 -> 'A'.
        # chunk1 = bits[6:8] (buffer ends at 1 byte, so only 2 bits exist) =
        # 0b01 = 1 -> 'A'. => "1.AA"
        (b"A", "1.AA"),
        # b"AB" = 0x41, 0x42. chunk0 = bits[0:6] of 0x41 = 1 -> 'A'.
        # chunk1 = bits[6:12] = top 2 bits of 0x41 (=0b01=1) then bottom 4
        # bits of 0x42 (0x42=0b01000010, bits[0:4]=0b0010=2), combined
        # LSB-first as 1 | (2<<2) = 9 -> 'I'. chunk2 = bits[12:18] = top 4
        # bits of 0x42 (bits[4:8]=0b0100=4) = 4 -> 'D'. => "2.AID"
        (b"AB", "2.AID"),
    ],
)
def test_juce_base64_encode_matches_hand_derived_vectors(data, expected):
    assert juce_base64_encode(data) == expected


@pytest.mark.parametrize(
    ("encoded", "expected"),
    [("1.AA", b"A"), ("2.AID", b"AB")],
)
def test_juce_base64_decode_matches_hand_derived_vectors(encoded, expected):
    assert juce_base64_decode(encoded) == expected


@pytest.mark.parametrize(
    "data",
    [
        b"",
        b"\x00",
        b"\xff",
        b"hello, vital!",
        bytes(range(256)),
        bytes((i * 37 + 5) % 256 for i in range(1000)),  # deterministic filler
        PRESET_JSON,
    ],
)
def test_juce_base64_round_trips_arbitrary_bytes(data):
    assert juce_base64_decode(juce_base64_encode(data)) == data


def test_juce_base64_round_trips_every_leftover_bit_count():
    # 6 doesn't divide 8, so the last char's bit alignment cycles through
    # every offset as length grows; exercise a full cycle (and then some).
    for length in range(0, 25):
        data = bytes(range(length))
        assert juce_base64_decode(juce_base64_encode(data)) == data


def test_juce_base64_decode_rejects_missing_length_prefix():
    with pytest.raises(RenderError, match="length prefix"):
        juce_base64_decode("no-dot-here")


def test_juce_base64_decode_skips_out_of_alphabet_characters():
    # JUCE's fromBase64Encoding silently skips characters it can't map,
    # rather than erroring - never triggered by real Vital data (the
    # alphabet has none of XML's reserved characters), but worth matching.
    assert juce_base64_decode("1.A B") == juce_base64_decode("1.AB")


# ------------------------------------------------------------- VC2! framing

def _vc2_frame(xml: str) -> bytes:
    xml_bytes = xml.encode("utf-8")
    return VC2_MAGIC + struct.pack("<I", len(xml_bytes)) + xml_bytes + b"\x00"


def _icomponent_xml(preset_json_bytes: bytes, iedit: str = "0.") -> str:
    b64 = juce_base64_encode(preset_json_bytes + b"\x00")
    return (
        '<?xml version="1.0" encoding="UTF-8"?> <VST3PluginState>'
        f"<IComponent>{b64}</IComponent>"
        f"<IEditController>{iedit}</IEditController>"
        "</VST3PluginState>"
    )


def test_parse_state_unwraps_vc2_frame():
    blob = parse_state(_vc2_frame(_icomponent_xml(PRESET_JSON)))
    assert blob.xml is not None
    assert blob.payload == json.loads(PRESET_JSON)
    assert blob.holds_vital_json
    assert blob.injectable


def test_parse_state_verifies_magic_bytes():
    raw = b"NOPE" + struct.pack("<I", 4) + b"junk"
    blob = parse_state(raw)
    assert blob.xml is None
    assert blob.payload is None


def test_parse_state_rejects_declared_length_past_end_of_buffer():
    xml_bytes = _icomponent_xml(PRESET_JSON).encode("utf-8")
    raw = VC2_MAGIC + struct.pack("<I", len(xml_bytes) + 10_000) + xml_bytes + b"\x00"
    blob = parse_state(raw)
    assert blob.xml is None
    assert blob.payload is None


def test_parse_state_handles_missing_icomponent_element():
    raw = _vc2_frame("<VST3PluginState><IEditController>0.</IEditController></VST3PluginState>")
    blob = parse_state(raw)
    assert blob.xml is not None
    assert blob.payload is None
    assert not blob.injectable


def test_parse_state_still_falls_back_to_bare_json_without_vc2_magic():
    blob = parse_state(PRESET_JSON)
    assert blob.xml is None
    assert blob.holds_vital_json
    assert blob.json_start == 0


def test_parse_state_reports_absence_rather_than_guessing():
    blob = parse_state(b"\x01\x02\x03 no json here")
    assert blob.payload is None
    assert blob.holds_vital_json is False
    assert not blob.injectable


# ---------------------------------------------------- inject / round-trip

def test_rebuild_with_injects_new_preset_and_preserves_wrapper():
    raw = _vc2_frame(_icomponent_xml(PRESET_JSON, iedit="7.ABCDEFG"))
    blob = parse_state(raw)

    new_preset = Preset.load(FIXTURES / "basic.vital")
    rebuilt = blob.rebuild_with(new_preset)

    assert rebuilt[:4] == VC2_MAGIC
    declared_len = struct.unpack_from("<I", rebuilt, 4)[0]
    assert declared_len == len(rebuilt) - 9  # frame invariant: len(raw) == 9 + xml_length
    assert rebuilt[8 + declared_len:] == b"\x00"  # single trailing NUL

    reparsed = parse_state(rebuilt)
    assert reparsed.payload == new_preset.data
    assert reparsed.holds_vital_json
    assert "<IEditController>7.ABCDEFG</IEditController>" in reparsed.xml  # untouched


def test_rebuild_with_round_trips_a_real_fixture_preset():
    blob = parse_state(_vc2_frame(_icomponent_xml(PRESET_JSON)))

    basic = Preset.load(FIXTURES / "basic.vital")
    brighter = Preset.load(FIXTURES / "brighter.vital")
    assert basic.data != brighter.data  # sanity: fixtures actually differ

    injected = parse_state(blob.rebuild_with(brighter))
    assert injected.payload == brighter.data
    assert injected.payload != basic.data


def test_rebuild_with_refuses_when_no_icomponent_element():
    blob = parse_state(_vc2_frame("<VST3PluginState></VST3PluginState>"))
    with pytest.raises(RenderError, match="no <IComponent>"):
        blob.rebuild_with(Preset.load(FIXTURES / "basic.vital"))
